<a href="https://colab.research.google.com/github/SANDESHAHAHA/Data-science2/blob/main/lossfunction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [71]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


**For logistic regression log loss is perfect **

In [72]:
y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [73]:
def mae(y_true,y_predicted):
    total_error=0
    # for loop in two arrays parallely we use zip function
    for yt,yp in zip(y_true,y_predicted):
        total_error += abs(yt-yp)
    print("Total error",total_error)
    mae=total_error/len(y_true)
    print("Mean Absolute Error",mae)
    return mae

In [74]:
mae(y_true,y_predicted)

Total error 2.5
Mean Absolute Error 0.5


np.float64(0.5)

In [75]:
y_predicted-y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [76]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [77]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.5)

In [78]:
np.sum(np.abs(y_predicted-y_true))
#mean absolute error

np.float64(2.5)

In [79]:
# using log loss it may create a 0 as outcome at many cases so we use epsilon
epsilon=1e-15
y_predicted
#now changing the value close to 1 but not 1 to prevent the above error




array([1, 1, 0, 0, 1])

In [80]:
# y_predicted_new=[max(i,epsilon) for i in y_predicted ]
# y_predicted_new


In [81]:
# y_final=[min(i,1-epsilon) for i in y_predicted_new]
# y_final

In [82]:
np.log(y_final)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [83]:
# np.log(y_predicted)

In [84]:
#clipping function works like : range bhitra paro bhane tettikai hunxa, ra thrshold sanga compare garda
#yedi threshold given value bhanda sano xa bhane threshold set hunxa ra yedi given value threshold bhanda thulo xa bhane pani threshold set hunxa
#example given at last

y_predicted_new=np.clip(y_predicted,epsilon,1-epsilon)
y_predicted_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [85]:
# this is log loss/ binary cross entropy
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(17.2696280766844)

In [86]:
arr = np.array([0, 0.5, 1, 2])
clipped = np.clip(arr, 0.1, 0.9)
print(clipped)

[0.1 0.5 0.9 0.9]
